### ISSUE TITLE
Add quick actions

### ISSUE THREAD

**Issue by dnsmichi** [NETWAYS/gitlab-advanced-training#1]
- Tags from commits
- More from issues/merge request commands

Docs: https://docs.gitlab.com/ee/user/project/quick_actions.html

**Comment by dnsmichi** [comment]
Let's see when this gets more prominent. We've been discussing them on Twitter/GitLab and people need to be educated on their usage, seems not well known.

**Comment by martialblog** [comment]
The training will be refactored in the future. Closing this issue for now
