### ISSUE TITLE
CI/CD: Anchors, extends, hidden keys for re-usable configuration

### ISSUE THREAD

**Issue by dnsmichi** [NETWAYS/gitlab-advanced-training#13]
https://www.netways.de/blog/2019/11/21/gitlab-ci-yaml-write-less-with-anchors-extends-and-hidden-keys/
https://gitlab.com/help/ci/yaml/README#yaml-anchors-for-before_script-and-after_script

https://gitlab.com/gitlab-org/gitlab-foss/issues/51367

https://medium.com/@rossinigiovanni/gitlab-ci-how-to-reuse-your-yml-code-96a82b3d587e

**Comment by dnsmichi** [comment]
Hard to create an example with many things to write, but let's see. This is a good thing for the advanced training and should be added imho.

**Comment by martialblog** [comment]
The training will be refactored in the future. Closing this issue for now
