### ISSUE TITLE
CI/CD: Multi cloud, Auto Devops, k8s

### ISSUE THREAD

**Issue by dnsmichi** [NETWAYS/gitlab-advanced-training#2]
- The how and why of app deployments into containers & cloud
- Introduction into Kubernetes
- Multi-cloud services
- Auto-Devops Template pipelines
- Security scanning

Mention learned best practices:

- Deployments to prod and staging
  - Explain environments: https://docs.gitlab.com/ee/ci/environments.html
  - Create an exercise based on different environments: https://about.gitlab.com/blog/2016/08/26/ci-deployment-and-environments/
- Leverage that developers don't need to care about containers, esp. web pages should just be accessible in the cloud
- Crossplane in 12.5

**Comment by dnsmichi** [comment]
Undecided, since you cannot really showcase that.

**Comment by martialblog** [comment]
The training will be refactored in the future. Closing this issue for now
