### ISSUE TITLE
Container Registry: Add best practices

### ISSUE THREAD

**Issue by dnsmichi** [NETWAYS/gitlab-advanced-training#3]
- Multiple distributions, multiple languages
- git.icinga.com build tools
- Packaging best practices
- Programming language examples

**Comment by dnsmichi** [comment]
GitLab will be adding new registries and binary asset possibilities in 2020, therefore it makes sense to add this at a later point.

**Comment by martialblog** [comment]
The training will be refactored in the future. Closing this issue for now
