### ISSUE TITLE
Monitoring: Prometheus & Grafana dashboards for CI/CD

### ISSUE THREAD

**Issue by dnsmichi** [NETWAYS/gitlab-advanced-training#7]
- TBD.

https://docs.gitlab.com/ee/administration/monitoring/performance/index.html
https://docs.gitlab.com/ee/administration/monitoring/gitlab_instance_administration_project/index.html
https://docs.gitlab.com/ee/administration/monitoring/prometheus/index.html
https://docs.gitlab.com/ee/user/project/integrations/prometheus.html#monitoring-cicd-environments
https://about.gitlab.com/blog/2018/09/27/why-all-organizations-need-prometheus/

**Comment by dnsmichi** [comment]
Re-scheduling this for later, the observability suite is moving to core in 2020.

**Comment by martialblog** [comment]
The training will be refactored in the future. Closing this issue for now
