### ISSUE TITLE
CI/CD: Code coverage report exercise

### ISSUE THREAD

**Issue by dnsmichi** [NETWAYS/gitlab-advanced-training#8]
- Write a Go test as exercise
  - Create a new formatting function which returns a string
  - Write a test case or two
- Modify the CI settings
- Inspect the coverage report in the jobs view
- Let the students add a coverage badge to their README.md 

https://docs.gitlab.com/ee/user/project/pipelines/settings.html#test-coverage-parsing
https://docs.gitlab.com/ee/user/project/pipelines/settings.html#test-coverage-report-badge

**Comment by dnsmichi** [comment]
That makes sense as standalone example after adding and fixing the CI config, before the container image creation.

**Comment by martialblog** [comment]
The training will be refactored in the future. Closing this issue for now
